name: Build & Publish (uv)

on:
  push:
    branches: [main]          # every commit to main → Test PyPI
    tags:     ['v*.*.*']      # tags like v0.2.0 → production PyPI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Install uv – fastest path for build & publish
      - uses: astral-sh/setup-uv@v2   # v2 auto-adds uv to PATH

      - name: Build wheel + sdist
        run: uv build                 # outputs to dist/

      # ------------------------------------------------------------------
      # Publish to Test PyPI on *non-tag* pushes
      # ------------------------------------------------------------------
      - name: Publish to Test PyPI
        if: startsWith(github.ref, 'refs/heads/')   # only branch pushes
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.TEST_PYPI_TOKEN }}
          UV_PUBLISH_URL:   https://test.pypi.org/legacy/
        run: uv publish dist/*

      # ------------------------------------------------------------------
      # Publish to production PyPI on version tags like v0.2.0
      # ------------------------------------------------------------------
      - name: Publish to PyPI
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: uv publish dist/*
